import Link from "next/link";
import { products } from "@/lib/products";
import { ProductCard } from "@/components/products/ProductCard";

export default function HomePage() {
  const featured = products.filter((product) => product.featured);
  const categories = Array.from(new Set(products.map((product) => product.category)));
  return <main><section className="mx-auto grid max-w-7xl items-center gap-10 px-6 py-20 md:grid-cols-2 md:py-28"><div><p className="font-semibold uppercase tracking-[0.2em] text-indigo-600">Everyday essentials</p><h1 className="mt-4 max-w-2xl text-5xl font-bold leading-tight md:text-7xl">Good products. <span className="text-indigo-600">Better living.</span></h1><p className="mt-6 max-w-lg text-lg leading-8 text-slate-600">Thoughtfully selected goods designed to make your everyday life simpler, smarter, and more enjoyable.</p><Link href="/products" className="mt-8 inline-block rounded-full bg-indigo-600 px-7 py-3.5 font-semibold text-white hover:bg-indigo-700">Explore products →</Link></div><div className="flex min-h-80 items-center justify-center rounded-3xl bg-gradient-to-br from-indigo-100 via-purple-100 to-pink-100 text-9xl" aria-hidden="true">🛍️</div></section><section className="mx-auto max-w-7xl px-6 py-10"><p className="font-semibold uppercase tracking-wide text-indigo-600">Shop by mood</p><div className="mt-5 grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{categories.map((category) => <Link key={category} href={`/categories/${category.toLowerCase()}`} className="rounded-2xl border border-slate-200 p-6 font-semibold hover:border-indigo-500 hover:bg-indigo-50">{category}<span className="mt-2 block text-sm font-normal text-slate-500">Explore the collection →</span></Link>)}</div></section><section className="mx-auto max-w-7xl px-6 py-16"><div className="mb-8 flex items-end justify-between"><div><p className="font-semibold uppercase tracking-wide text-indigo-600">Our collection</p><h2 className="mt-2 text-3xl font-bold">Featured products</h2></div><Link href="/products" className="font-semibold hover:text-indigo-600">View all →</Link></div><div className="grid gap-6 sm:grid-cols-2 lg:grid-cols-4">{featured.map((product) => <ProductCard key={product.id} product={product} />)}</div></section></main>;
}
